[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "zjet-corrections"
version = "0.1.0"
dependencies = ["correctionlib>=2.2"]

[tool.setuptools.package-data]
"zjet_corrections" = ["corrections/**/*"]
